// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TicTacToe$ReactTemplate = require("./TicTacToe.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, TicTacToe$ReactTemplate.make("Tic Tac Toe!", /* array */[])), "index");

/*  Not a pure module */
